site_name: RevJS
pages:
  - Welcome to RevJS!: index.md
  - Components: components.md
strict: true
theme: readthedocs
extra_css:
  - style.css
docs_dir: /mkdocs/src
site_dir: /mkdocs/dist
repo_url: https://github.com/RevJS/revjs
edit_uri: /RevJS/revjs/edit/master/docs/mkdocs/src/