site_name: RevJS Guide
pages:
  - Welcome to RevJS!: index.md
  - Working with Models:
    - Defining Models: using_models/creating_models.md
    - Adding Validation: using_models/model_validation.md
    - Storage Backends: using_models/revjs_backends.md
    - Creating Data: using_models/creating_data.md
    - Reading Data: using_models/reading_data.md
    - Updating Data: using_models/updating_data.md
    - Deleting Data: using_models/deleting_data.md
    - Working with Related Models: using_models/related_data.md
  - Creating a GraphQL API:
    - Creating an API: creating_an_api/overview.md
  - Creating a User Interface:
    - RevJS UI Overview: creating_a_ui/overview.md
  - RevJS Module Reference:
    - rev-models: components/rev-models.md
    - rev-api: components/rev-api.md
    - rev-ui: components/rev-ui.md
    - Change Log: changelog.md
strict: true
theme: readthedocs
docs_dir: /mkdocs/src
site_dir: /mkdocs/dist
repo_url: https://github.com/RevJS/revjs
edit_uri: /RevJS/revjs/edit/master/docs/mkdocs/src/
google_analytics: ['UA-115939002-1','revjs.org']
markdown_extensions:
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: /packages
extra_javascript:
  - js/highlight.pack.js
extra_css:
  - css/highlight.css
  - css/style.css