site_name: RevJS Guide
pages:
  - Welcome to RevJS!: index.md
  - Working with Models:
    - Defining Models: models/creating_models.md
    - Adding Validation: models/model_validation.md
    - Storage Backends: models/revjs_backends.md
    - Creating Data: models/creating_data.md
    - Reading Data: models/reading_data.md
    - Updating Data: models/updating_data.md
    - Deleting Data: models/deleting_data.md
    - Working with Related Models: models/related_data.md
  - Creating a GraphQL API:
    - Creating an API: api/creating_an_api.md
  - RevJS Module Reference:
    - rev-models: components/rev-models.md
    - rev-backend-mongodb: components/rev-backend-mongodb.md
    - rev-api: components/rev-api.md
    - rev-api-client: components/rev-api-client.md
    - rev-ui: components/rev-ui.md
    - Change Log: changelog.md
strict: true
theme: readthedocs
docs_dir: /mkdocs/src
site_dir: /mkdocs/dist
repo_url: https://github.com/RevJS/revjs
edit_uri: /RevJS/revjs/edit/master/docs/mkdocs/src/
google_analytics: ['UA-115939002-1','revjs.org']
markdown_extensions:
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: /packages
extra_javascript:
  - js/highlight.pack.js
extra_css:
  - css/highlight.css
  - css/style.css