site_name: RevJS
repo_url: https://github.com/RevJS/revjs
pages:
  - Welcome!:
    - What is RevJS?: index.md
    - Components: components.md
  - Components:
    - rev-models: components/models.md
strict: true
theme: readthedocs
docs_dir: /mkdocs/src
site_dir: /mkdocs/dist