site_name: RevJS Guide
pages:
  - Welcome to RevJS!: index.md
  - Components:
      - rev-models: rev-models.md
      - rev-api: rev-api.md
      - rev-api-client: rev-api-client.md
      - rev-ui: rev-ui.md
strict: true
theme: readthedocs
extra_css:
  - css/style.css
docs_dir: /mkdocs/src
site_dir: /mkdocs/dist
repo_url: https://github.com/RevJS/revjs
edit_uri: /RevJS/revjs/edit/master/docs/mkdocs/src/
markdown_extensions:
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: /packages
extra_javascript:
  - js/highlight.pack.js
extra_css:
  - css/highlight.css